# theme: argvus-dark-aether

[colors-dark]
foreground = DFE5EA
background = 111316
selection-foreground = DFE5EA
selection-background = 333647
regular0 = 111316
regular1 = a74a4a
regular2 = 4fae4d
regular3 = b3a352
regular4 = 3590bd
regular5 = b960b0
regular6 = 67b2bc
regular7 = DFE5EA
bright0 = 323841
bright1 = c47a7a
bright2 = 82c780
bright3 = cabf87
bright4 = 5dabd2
bright5 = d095ca
bright6 = 9ccdd3
bright7 = ffffff
cursor = 111316 DFE5EA
