# theme: rose-pine

[colors-dark]
foreground = E0DEF4
background = 191724
selection-foreground = E0DEF4
selection-background = 403D52
regular0 = 191724
regular1 = EB6F92
regular2 = 31748F
regular3 = F6C177
regular4 = 9CCFD8
regular5 = C4A7E7
regular6 = 9CCFD8
regular7 = E0DEF4
bright0 = 6E6A86
bright1 = EB6F92
bright2 = 31748F
bright3 = F6C177
bright4 = 9CCFD8
bright5 = C4A7E7
bright6 = 9CCFD8
bright7 = FFFFFF
cursor = 191724 E0DEF4
