# theme: argvus-catppuccin-latte

[colors-dark]
foreground = 4C4F69
background = EFF1F5
selection-foreground = 4C4F69
selection-background = ACB0BE
regular0 = EFF1F5
regular1 = 5b2c2c
regular2 = 295428
regular3 = 4d4725
regular4 = 4C4F69
regular5 = 3f1e3c
regular6 = 1b3538
regular7 = 4C4F69
bright0 = d1d1d1
bright1 = 271313
bright2 = 10200f
bright3 = 19170c
bright4 = 000000
bright5 = 0b050b
bright6 = 020404
bright7 = 000000
cursor = EFF1F5 4C4F69

