# theme: argvus-dark-hackerman-float

[colors-dark]
foreground = DDF7FF
background = 0B0C16
selection-foreground = DDF7FF
selection-background = 82FB9C
regular0 = 0B0C16
regular1 = E25D6C
regular2 = CEA37F
regular3 = F4BB54
regular4 = 82FB9C
regular5 = EDE4C8
regular6 = E8AB3B
regular7 = E6CAAB
bright0 = 706A6A
bright1 = E9838F
bright2 = CEA37F
bright3 = EDB95A
bright4 = 9DFFB2
bright5 = EDE4C8
bright6 = ECB95C
bright7 = DDF7FF
cursor = 0B0C16 DDF7FF
