# Argvus palette
# ---
# bg         "#f7f7f7"
# bg-2       "#f2f2f2"
# ui         "#ebebeb"
# ui-2       "#d8d8d8"
# ui-3       "#c7c7c7"
# tx-3       "#5a5a5a"
# tx-2       "#454545"
# tx         "#181818"
# red-400     "#9b2f3b" re
# orange-400  "#725a35" or
# yellow-400  "#303030" ye
# yellow-600  "#725a35" ye-2
# green-400   "#181818" gr
# cyan-400    "#181818" cy
# cyan-600    "#c7c7c7" cy-2
# cyan-700    "#c7c7c7" cy-700
# cyan-900    "#ebebeb" cy-900
# blue-400    "#181818" bl
# purple-400  "#303030" pu
# magenta-400 "#9b2f3b" ma

[app]
overall = { bg = "#f7f7f7" } # bg

[mgr]
cwd = { fg = "#181818", bold = true } # tx

# Find
find_keyword = { fg = "#181818", reversed = true } # cy
find_position = { fg = "#181818", bold = true, italic = true } # cy

# Marker
marker_copied = { fg = "#181818", bg = "#181818" } # gr, gr
marker_cut = { fg = "#9b2f3b", bg = "#9b2f3b" } # re, re
marker_marked = { fg = "#c7c7c7", bg = "#c7c7c7" } # cy-700, cy-700
marker_selected = { fg = "#181818", bg = "#181818" } # cy, cy

# Count
count_copied = { fg = "#181818", bold = true, reversed = true } # gr
count_cut = { fg = "#9b2f3b", bold = true, reversed = true } # re
count_selected = { fg = "#181818", bold = true, reversed = true } # cy

# Border
border_symbol = "│"
border_style = { fg = "#ebebeb" } # ui

[indicator]
parent = { underline = true }
current = { fg = "#181818", bg = "#ebebeb" } # tx, ui
preview = { underline = true }
padding = { open = "█", close = "█" }

[tabs]
active = { fg = "#181818", bg = "#c7c7c7", bold = true } # tx, ui-3
inactive = { fg = "#454545", bg = "#ebebeb" } # tx-2, ui
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
# Normal mode
normal_main = { fg = "#181818", bg = "#c7c7c7", bold = true } # tx, ui-3
normal_alt = { fg = "#454545", bg = "#ebebeb" } # tx-2, ui

# Select mode
select_main = { fg = "#f7f7f7", bg = "#181818", bold = true } # bg, cy
select_alt = { fg = "#181818", bg = "#ebebeb" } # cy, cy-900

# Unset mode
unset_main = { fg = "#f7f7f7", bg = "#181818", bold = true } # bg, cy
unset_alt = { fg = "#181818", bg = "#ebebeb" } # cy, cy-900

[status]
overall = { fg = "#181818" } # tx

# Permissions
perm_type = { fg = "#181818" } # bl
perm_read = { fg = "#303030" } # ye
perm_write = { fg = "#9b2f3b" } # re
perm_exec = { fg = "#181818" } # gr
perm_sep = { fg = "#454545" } # tx-2

# Progress
progress_label = { fg = "#f7f7f7" } # bg
progress_normal = { fg = "#181818", bg = "#c7c7c7" } # cy, cy-700
progress_error = { bg = "#9b2f3b" } # re

[which]
cols = 3
mask = { bg = "#f2f2f2" } # bg-2
cand = { fg = "#181818", bold = true } # cy
rest = { fg = "#181818", italic = true } # cy
desc = { fg = "#5a5a5a" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#c7c7c7" } # ui-3
title = { fg = "#5a5a5a", bold = true } # tx-3
body = { fg = "#181818", bold = true } # tx
list = { fg = "#181818" } # tx
btn_yes = { fg = "#181818", bg = "#c7c7c7", bold = true } # tx, ui-3
btn_no = { fg = "#454545", bg = "#ebebeb" } # tx-2, ui

[spot]
border = { fg = "#c7c7c7" } # ui-3
title = { fg = "#5a5a5a", bold = true } # tx-3
tbl_col = { fg = "#454545" } # tx-2
tbl_cell = { fg = "#181818", bg = "#ebebeb" } # tx, ui

[notify]
# Notification title
title_info = { fg = "#181818" } # bl
title_warn = { fg = "#725a35" } # or
title_error = { fg = "#9b2f3b" } # re

[pick]
border = { fg = "#c7c7c7", bold = true } # ui-3
active = { fg = "#181818" } # tx
inactive = { fg = "#454545" } # tx-2

[input]
border = { fg = "#c7c7c7" } # ui-3
title = { fg = "#5a5a5a", bold = true } # tx-3
value = { fg = "#181818" } # tx
selected = { bg = "#f2f2f2" } # bg-2

[cmp]
border = { fg = "#c7c7c7", bold = true } # ui-3
active = { fg = "#181818", bg = "#ebebeb" } # tx, ui
inactive = { fg = "#454545" } # tx-2

[tasks]
border = { fg = "#c7c7c7" } # ui-3
title = { fg = "#5a5a5a", bold = true } # tx-3
hovered = { fg = "#181818", bg = "#ebebeb" } # tx, ui

[help]
on = { fg = "#181818" } # bl
run = { fg = "#181818" } # cy
desc = { fg = "#5a5a5a", italic = true } # tx-3
hovered = { bg = "#ebebeb" } # ui
footer = { fg = "#f7f7f7", bg = "#181818", bold = true } # bg, cy

[filetype]
rules = [
  # Empty files
  { mime = "inode/empty", fg = "#5a5a5a" }, # tx-3

  # Special files
  { url = "*", is = "orphan", fg = "#5a5a5a" }, # tx-3
  { url = "*/", is = "orphan", fg = "#5a5a5a" }, # tx-3
  { url = "*", is = "link", fg = "#181818" }, # cy
  { url = "*/", is = "link", fg = "#181818" }, # cy
  { url = "*", is = "block", fg = "#181818" }, # tx
  { url = "*", is = "char", fg = "#181818" }, # tx
  { url = "*", is = "fifo", fg = "#9b2f3b" }, # ma
  { url = "*", is = "sock", fg = "#9b2f3b" }, # ma
  { url = "*", is = "sticky", fg = "#181818" }, # tx
  { url = "*", is = "dummy", fg = "#5a5a5a" }, # tx-3

  # Fallback
  { url = "*/", fg = "#181818" }, # tx
  { url = "*", is = "exec", fg = "#181818" }, # gr
  { url = "*", fg = "#454545" } # tx-2
]

[icon]
dirs = [
  { name = ".config", text = "", fg = "#181818" }, # cy
  { name = ".git", text = "", fg = "#181818" }, # cy
  { name = ".github", text = "", fg = "#181818" }, # cy
  { name = ".npm", text = "", fg = "#181818" }, # cy
  { name = "Desktop", text = "", fg = "#181818" }, # cy
  { name = "Development", text = "", fg = "#181818" }, # cy
  { name = "Documents", text = "", fg = "#181818" }, # cy
  { name = "Downloads", text = "", fg = "#181818" }, # cy
  { name = "Library", text = "", fg = "#181818" }, # cy
  { name = "Movies", text = "", fg = "#181818" }, # cy
  { name = "Music", text = "", fg = "#181818" }, # cy
  { name = "Pictures", text = "", fg = "#181818" }, # cy
  { name = "Public", text = "", fg = "#181818" }, # cy
  { name = "Videos", text = "", fg = "#181818" } # cy
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#5a5a5a" }, # tx-3
  { if = "link", text = "", fg = "#181818" }, # cy
  { if = "block", text = "", fg = "#181818" }, # tx
  { if = "char", text = "", fg = "#181818" }, # tx
  { if = "fifo", text = "", fg = "#9b2f3b" }, # ma
  { if = "sock", text = "", fg = "#9b2f3b" }, # ma
  { if = "sticky", text = "", fg = "#181818" }, # tx
  { if = "dummy", text = "", fg = "#5a5a5a" }, # tx-3

  # Fallback
  { if = "dir", text = "", fg = "#181818" }, # cy
  { if = "exec", text = "", fg = "#181818" }, # gr
  { if = "!dir", text = "", fg = "#454545" } # tx-2
]