# theme: solarized-light-float
[colors-dark]
foreground = 657B83
background = FDF6E3
selection-foreground = 657B83
selection-background = EEE8D5
regular0 = 073642
regular1 = DC322F
regular2 = 859900
regular3 = B58900
regular4 = 268BD2
regular5 = D33682
regular6 = 2AA198
regular7 = EEE8D5
bright0 = 586E75
bright1 = CB4B16
bright2 = 859900
bright3 = B58900
bright4 = 268BD2
bright5 = 6C71C4
bright6 = 2AA198
bright7 = FDF6E3
cursor = FDF6E3 657B83
