# theme: argvus-tokyo-night

[colors-dark]
foreground = C0CAF5
background = 1A1B26
selection-foreground = C0CAF5
selection-background = 3B4261
regular0 = 15161E
regular1 = F7768E
regular2 = 9ECE6A
regular3 = E0AF68
regular4 = 7AA2F7
regular5 = BB9AF7
regular6 = 7DCFFF
regular7 = C0CAF5
bright0 = 414868
bright1 = F7768E
bright2 = 9ECE6A
bright3 = E0AF68
bright4 = 7AA2F7
bright5 = BB9AF7
bright6 = 7DCFFF
bright7 = ffffff
cursor = 1A1B26 C0CAF5
