# theme: argvus-dark-monokai-float
[colors-dark]
foreground = FCFCFA
background = 2D2A2E
selection-foreground = FCFCFA
selection-background = 403E41
regular0 = 19181A
regular1 = FF6188
regular2 = A9DC76
regular3 = FFD866
regular4 = 78DCE8
regular5 = AB9DF2
regular6 = 78DCE8
regular7 = FCFCFA
bright0 = 727072
bright1 = FF6188
bright2 = A9DC76
bright3 = FFD866
bright4 = 78DCE8
bright5 = AB9DF2
bright6 = 78DCE8
bright7 = FFFFFF
cursor = 19181A FCFCFA
