# theme: argvus-dark-universe

[colors-dark]
foreground = EEEEEE
background = 000000
selection-foreground = EEEEEE
selection-background = 1a1a1a
regular0 = 000000
regular1 = c48585
regular2 = 8dc88c
regular3 = cbc293
regular4 = EEEEEE
regular5 = d2a1cd
regular6 = a8d0d5
regular7 = EEEEEE
bright0 = 262626
bright1 = ddb9b9
bright2 = c0e1c0
bright3 = e4dfc7
bright4 = ffffff
bright5 = ebd5e9
bright6 = dcecee
bright7 = ffffff
cursor = 000000 EEEEEE
