# theme: argvus-frost

[colors-dark]
foreground = 24292F
background = F6F8FA
selection-foreground = 24292F
selection-background = DDF4FF
regular0 = F6F8FA
regular1 = CF222E
regular2 = 1A7F37
regular3 = 9A6700
regular4 = 0969DA
regular5 = 8250DF
regular6 = 087EA4
regular7 = 24292F
bright0 = D0D7DE
bright1 = A40E26
bright2 = 116329
bright3 = 7D4E00
bright4 = 0550AE
bright5 = 6639BA
bright6 = 056B8A
bright7 = FFFFFF
cursor = FFFFFF 0969DA
