# theme: argvus-dark-silver-float

[colors-dark]
foreground = DFE5EA
background = 111316
selection-foreground = DFE5EA
selection-background = 333647
regular0 = 111316
regular1 = 8d4444
regular2 = 499447
regular3 = 9b8e4a
regular4 = 595959
regular5 = a851a0
regular6 = 56a3ae
regular7 = DFE5EA
bright0 = 323841
bright1 = b66868
bright2 = 70b96e
bright3 = bdb175
bright4 = 787878
bright5 = c383bd
bright6 = 8abfc7
bright7 = ffffff
cursor = 111316 DFE5EA
