# theme: argvus-dark-sunset-float

[colors-dark]
foreground = EADCCC
background = 0F0F0F
selection-foreground = EADCCC
selection-background = E2BE8A
regular0 = 0F0F0F
regular1 = E25D6C
regular2 = CEA37F
regular3 = F4BB54
regular4 = E2BE8A
regular5 = EDE4C8
regular6 = E8AB3B
regular7 = E6CAAB
bright0 = 706A6A
bright1 = E9838F
bright2 = CEA37F
bright3 = EDB95A
bright4 = EACEA7
bright5 = EDE4C8
bright6 = ECB95C
bright7 = EADCCC
cursor = 0F0F0F EADCCC
