# theme: argvus-dark-solitude-float

[colors-dark]
foreground = CACCCC
background = 101315
selection-foreground = CACCCC
selection-background = 343D41
regular0 = 101315
regular1 = 565D60
regular2 = 9FA5A9
regular3 = D9DBDC
regular4 = 798186
regular5 = AEAEAE
regular6 = 707070
regular7 = CACCCC
bright0 = 4B4E55
bright1 = DE6145
bright2 = 343D41
bright3 = C9C2B4
bright4 = 5D6367
bright5 = 9A9A9A
bright6 = 707070
bright7 = A5AEB4
cursor = 101315 CACCCC
