# theme: argvus-light-frost-float

code_syntax_highlight = "catppuccin-macchiato"

full_screen_fg = "#24292F"
full_screen_bg = "#F6F8FA"
gradient_color = ["#24292F", "#57606A"]

file_panel_fg = "#24292F"
file_panel_bg = "#F6F8FA"
file_panel_border = "#B8C1CC"
file_panel_border_active = "#24292F"
file_panel_top_directory_icon = "#24292F"
file_panel_top_path = "#24292F"
file_panel_item_selected_fg = "#24292F"
file_panel_item_selected_bg = "#F1F4F7"

footer_fg = "#24292F"
footer_bg = "#F6F8FA"
footer_border = "#B8C1CC"
footer_border_active = "#24292F"

sidebar_fg = "#24292F"
sidebar_bg = "#F6F8FA"
sidebar_title = "#24292F"
sidebar_border = "#B8C1CC"
sidebar_border_active = "#24292F"
sidebar_item_selected_fg = "#24292F"
sidebar_item_selected_bg = "#F1F4F7"
sidebar_divider = "#B8C1CC"

modal_fg = "#24292F"
modal_bg = "#F6F8FA"
modal_border_active = "#24292F"
modal_cancel_fg = "#F6F8FA"
modal_cancel_bg = "#57606A"
modal_confirm_fg = "#F6F8FA"
modal_confirm_bg = "#24292F"

help_menu_hotkey = "#24292F"
help_menu_title = "#24292F"

cursor = "#24292F"
correct = "#24292F"
error = "#57606A"
hint = "#24292F"
cancel = "#57606A"
