# theme: argvus-dark-slate

[colors-dark]
foreground = A6B8C4
background = 2F3541
selection-foreground = 2F3541
selection-background = 7391a5
regular0 = 2F3541
regular1 = af5959
regular2 = 62b360
regular3 = b6a967
regular4 = A6B8C4
regular5 = bd75b5
regular6 = 7cb8c0
regular7 = A6B8C4
bright0 = 4f596d
bright1 = c88d8d
bright2 = 95cc94
bright3 = cfc69b
bright4 = cbd5dc
bright5 = d6a9d1
bright6 = b0d4d9
bright7 = d4dde2
cursor = 2F3541 A6B8C4
