# theme: argvus-dark-gruvbox

[colors-dark]
foreground = EBDBB2
background = 282828
selection-foreground = EBDBB2
selection-background = 665C54
regular0 = 282828
regular1 = a74a4a
regular2 = 4fae4d
regular3 = b3a352
regular4 = D4BE98
regular5 = b960b0
regular6 = 67b2bc
regular7 = EBDBB2
bright0 = 323841
bright1 = c47a7a
bright2 = 82c780
bright3 = cabf87
bright4 = 5dabd2
bright5 = d095ca
bright6 = 9ccdd3
bright7 = ffffff
cursor = 282828 EBDBB2
